#!/bin/bash

set -e

echo
echo "##################################"
echo "#  Na jaký počítač instalujete?  #"
echo "#  Zbook = 1                     #"
echo "#  Probook = 2                   #"
echo "#  Mirantb = 3                   #"
echo "##################################"

while true; do
    read -r -n 1 -p " Vyberte 1/2/3: " answer
    case $answer in
        [1]* ) echo
               echo "###########################"
               echo "#                         #"
               echo "#  Zvolili jste Zbook...  #"
               echo "#                         #"
               echo "###########################"
               echo
               sleep 4 
               break;;
        [2]* ) echo
               echo "#############################"
               echo "#                           #"
               echo "#  Zvolili jste Probook...  #"
               echo "#                           #"
               echo "#############################"
               echo
               sleep 4 
               break;;
        [3]* ) echo
               echo "#############################"
               echo "#                           #"
               echo "#  Zvolili jste Mirantb...  #"
               echo "#                           #"
               echo "#############################"
               echo
               sleep 4
               break;;
         * ) echo "Vyberte 1, 2, nebo 3";;
     esac
done

echo
echo "#######################"
echo "#  Instalace balíčků  #"
echo "#######################"
sleep 2
sudo zypper install \
    brave-browser brightnessctl btop cliphist dnf-plugins-core evince fastfetch fd ffmpeg \
    firewall-applet firewalld fish foot fzf \
    galculator gawk gcc geany gparted gvfs hplip ImageMagick jq jetbrains-mono-fonts \
    libqt5-qtwayland libreoffice libxcb-devel \
    mako make nemo NetworkManager-applet ncurses-devel nfs-client niri nwg-look \
    opi pamixer papirus-icon-theme pavucontrol power-profiles-daemon \
    qutebrowser qt6ct resvg ripgrep ristretto \
    simple-scan swaybg swayidle swaylock system-config-printer \
    consoleet-terminus-fonts udiskie udisks2 \
    waybar wayland-devel wayland-protocols-devel wget wireplumber wl-clipboard wlsunset \
    xcb-util-cursor xdg-desktop-portal-gnome yazi youtube-dl zenity zoxide 

cd $HOME
mkdir -p Dokumenty Videa Hudba Stažené Templates

case $answer in
    [1]* ) echo
           echo "####################################"
           echo "#                                  #"
           echo "#  Probíhá konfigurace Zbook...    #"
           echo "#                                  #"
           echo "####################################"
           git clone --bare -b tumbleweed https://github.com/lrestj/zbook.git $HOME/.cfg.git
           git --git-dir=$HOME/.cfg.git/ --work-tree=$HOME checkout -f &&
           echo
           echo "###################################"
           echo "#  Konfigurace git repozitáře...  #"
           echo "###################################"
           git config --global user.email "rest@seznam.cz"
           git config --global user.name "LrestJ"
           git --git-dir=$HOME/.cfg.git/ --work-tree=$HOME remote remove origin
           git --git-dir=$HOME/.cfg.git/ --work-tree=$HOME remote add github git@github.com:lrestj/zbook.git
           git --git-dir=$HOME/.cfg.git/ --work-tree=$HOME remote add gitlab git@gitlab.com:lrestj/zbook.git
           git --git-dir=$HOME/.cfg.git/ --work-tree=$HOME remote -v
           ;;
    [2]* ) echo
           echo "######################################"
           echo "#                                    #"
           echo "#  Probíhá konfigurace Probook...    #"
           echo "#                                    #"
           echo "######################################"
           git clone --bare -b fedora https://github.com/lrestj/probook.git $HOME/.cfg.git
           git --git-dir=$HOME/.cfg.git/ --work-tree=$HOME checkout -f &&
           echo
           echo "###################################"
           echo "#  Konfigurace git repozitáře...  #"
           echo "###################################"
           git config --global user.email "rest@seznam.cz"
           git config --global user.name "LrestJ"
           git --git-dir=$HOME/.cfg.git/ --work-tree=$HOME remote remove origin
           git --git-dir=$HOME/.cfg.git/ --work-tree=$HOME remote add github git@github.com:lrestj/probook.git
           git --git-dir=$HOME/.cfg.git/ --work-tree=$HOME remote add gitlab git@gitlab.com:lrestj/probook.git
           git --git-dir=$HOME/.cfg.git/ --work-tree=$HOME remote -v
           ;;
    [3]* ) echo
           echo "######################################"
           echo "#                                    #"
           echo "#  Probíhá konfigurace Mirantb...    #"
           echo "#                                    #"
           echo "######################################"
           git clone --bare -b debian https://github.com/lrestj/mirantb.git $HOME/.cfg.git
           git --git-dir=$HOME/.cfg.git/ --work-tree=$HOME checkout -f &&
           echo
           echo "###################################"
           echo "#  Konfigurace git repozitáře...  #"
           echo "###################################"
           git config --global user.email "rest@seznam.cz"
           git config --global user.name "LrestJ"
           git --git-dir=$HOME/.cfg.git/ --work-tree=$HOME remote remove origin
           git --git-dir=$HOME/.cfg.git/ --work-tree=$HOME remote add github git@github.com:lrestj/mirantb.git
           git --git-dir=$HOME/.cfg.git/ --work-tree=$HOME remote add gitlab git@gitlab.com:lrestj/mirantb.git
           git --git-dir=$HOME/.cfg.git/ --work-tree=$HOME remote -v
           ;;
     * ) echo "Vyberte 1, 2, nebo 3";;
esac

git clone https://github.com/lrestj/install $HOME/.dotfiles/install/
cd $HOME/.dotfiles/install/
git config --global user.email "rest@seznam.cz"
git config --global user.name "LrestJ"
git remote remove origin
git remote add github git@github.com:lrestj/install.git
git remote add gitlab git@gitlab.com:lrestj/install.git
git remote -v

echo    
echo "#######################################"
echo "#  Autologin & firewall & swappiness  #"
echo "#######################################"
sudo cp -rf $HOME/.dotfiles/getty@tty1.service.d /etc/systemd/system/
sudo systemctl enable firewalld.service
sudo mkdir -p /etc/sysctl.d
echo vm.swappiness=10 | sudo tee /etc/sysctl.d/99-swappiness.conf
sudo cp -rv /home/libor/.dotfiles/journald.conf.d /etc/systemd/
gsettings set org.cinnamon.desktop.default-applications.terminal exec foot
sudo powerprofilesctl set performance
sudo cp -r /home/libor/.local/share/icons/Bibata-Modern-Classic /usr/share/icons/

echo
echo "###########################"
echo "#  Nfs Synology settings  #"
echo "###########################"
sudo cp -v /etc/fstab /etc/fstab.bak
cat $HOME/.dotfiles/nfs2fstab.txt | sudo tee -a /etc/fstab >> /dev/null

case $answer in
    [1]* ) echo
           echo "###########################"
           echo "#  Nvidia driver install  #"
           echo "###########################"
           sudo zypper install -y nvidia-driver-G06-kmp-meta
           break;;
    * ) exit;;
esac

echo
echo "#####################"
echo "#  Instalace Brave  #"
echo "#####################"
echo
opi brave
echo
echo "#####################"
echo "#  Konec instalace  #"
echo "#####################"
echo
echo "####################################"
echo "#  Restartovat do nového systému?  #"
echo "####################################"
while true; do
    read -r -n 1 -p "Vyberte (A/N): " answer
    case $answer in
        [Aa]* ) echo -e "\n Restartuji..."
                sleep 1
                sudo reboot; break;;
        [Nn]* ) exit;;
        * ) echo -e "\nVyberte A nebo N.";;
    esac
done

###  END OF FILE  ###
